# ==============================================================================
# Workflow GitHub Actions pour la Suite d'Analyse BRVM Complète (V1.3)
# ==============================================================================
name: Full BRVM Analysis Suite

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-analysis-suite:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Chrome for Selenium
        uses: browser-actions/setup-chrome@latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BRVM Analysis Suite
        env:
          # MODIFIÉ : On passe explicitement TOUTES les clés numérotées
          GSPREAD_SERVICE_ACCOUNT: ${{ secrets.GSPREAD_SERVICE_ACCOUNT }}
          GOOGLE_API_KEY_1: ${{ secrets.GOOGLE_API_KEY_1 }}
          GOOGLE_API_KEY_2: ${{ secrets.GOOGLE_API_KEY_2 }}
          GOOGLE_API_KEY_3: ${{ secrets.GOOGLE_API_KEY_3 }}
          GOOGLE_API_KEY_4: ${{ secrets.GOOGLE_API_KEY_4 }}
          GOOGLE_API_KEY_5: ${{ secrets.GOOGLE_API_KEY_5 }}
        run: python main.py

      - name: Upload Synthesis Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Rapport-Synthese-Investissement-BRVM
          path: |
            ./Rapport_Synthese_*.docx
