# ==============================================================================
# Workflow GitHub Actions pour la Suite d'Analyse BRVM Complète
# ==============================================================================
name: Full BRVM Analysis Suite

on:
  schedule:
    # MODIFICATION ICI : S'exécute tous les lundis à 07h00 UTC
    - cron: '0 7 * * 1'
  
  # Permet de lancer manuellement le workflow depuis l'onglet "Actions" de GitHub
  workflow_dispatch:

jobs:
  run-analysis-suite:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code de votre dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure Chrome pour Selenium (nécessaire pour l'analyse fondamentale)
      - name: Setup Chrome for Selenium
        uses: browser-actions/setup-chrome@latest

      # 3. Configure l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 4. Installe les dépendances Python via requirements.txt
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Exécute la suite d'analyse complète via le script principal
      - name: Run BRVM Analysis Suite
        env:
          # Passe les secrets au script
          GSPREAD_SERVICE_ACCOUNT: ${{ secrets.GSPREAD_SERVICE_ACCOUNT }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python main.py

      # 6. Sauvegarde le rapport de synthèse final comme un "artifact"
      - name: Upload Synthesis Report Artifact
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: Rapport-Synthese-Investissement-BRVM
          path: |
            ./Rapport_Synthese_*.docx
