# ==============================================================================
# FICHIER TEMPORAIRE - WORKFLOW DE TEST POUR LE NOUVEAU DATA COLLECTOR
# ==============================================================================
name: Full BRVM Analysis Suite

on:
  workflow_dispatch:

jobs:
  run-new-data-collector:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run New Data Collector
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: python data_collector.py
