# ==============================================================================
# WORKFLOW FINAL - ARCHITECTURE POSTGRESQL (V2.1 - PRODUCTION)
# ==============================================================================
name: Full BRVM Analysis Suite (DB Architecture)

on:
  schedule:
    # S'exécute tous les jours à 07h00 UTC
    - cron: '0 7 * * *'
  
  workflow_dispatch: # Permet le lancement manuel

jobs:
  run-full-suite:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # La section 'with: ref: develop' a été supprimée.
        # Par défaut, l'action utilisera la branche 'main'.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev build-essential libssl-dev libffi-dev python3-dev libxml2-dev libxslt1-dev libjpeg-dev zlib1g-dev xvfb

      - name: Install Python Dependencies
        run: pip install --no-cache-dir -r requirements.txt
      
      - name: Setup Chrome for Selenium
        uses: browser-actions/setup-chrome@latest

      - name: Run Full Analysis Suite
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          GSPREAD_SERVICE_ACCOUNT: ${{ secrets.GSPREAD_SERVICE_ACCOUNT }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          # ... (toutes vos clés API) ...
        run: xvfb-run -a python main.py
        
      - name: Upload Reports Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Rapports-BRVM-Analyse-DB
          path: |
            ./Rapport_*.docx
            ./Synthese_*.docx
