# ==============================================================================
# Workflow GitHub Actions pour la Suite d'Analyse BRVM Complète (V1.7 - Final)
# ==============================================================================
name: Full BRVM Analysis Suite

on:
  schedule:
    # S'exécute tous les jours à 07h00 UTC
    - cron: '0 7 * * *'
  
  workflow_dispatch:

jobs:
  run-analysis-suite:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Chrome for Selenium
        uses: browser-actions/setup-chrome@latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BRVM Analysis Suite
        env:
          GSPREAD_SERVICE_ACCOUNT: ${{ secrets.GSPREAD_SERVICE_ACCOUNT }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          GOOGLE_API_KEY_1: ${{ secrets.GOOGLE_API_KEY_1 }}
          GOOGLE_API_KEY_2: ${{ secrets.GOOGLE_API_KEY_2 }}
          GOOGLE_API_KEY_3: ${{ secrets.GOOGLE_API_KEY_3 }}
          GOOGLE_API_KEY_4: ${{ secrets.GOOGLE_API_KEY_4 }}
          GOOGLE_API_KEY_5: ${{ secrets.GOOGLE_API_KEY_5 }}
          GOOGLE_API_KEY_6: ${{ secrets.GOOGLE_API_KEY_6 }}
          GOOGLE_API_KEY_7: ${{ secrets.GOOGLE_API_KEY_7 }}
          GOOGLE_API_KEY_8: ${{ secrets.GOOGLE_API_KEY_8 }}
          GOOGLE_API_KEY_9: ${{ secrets.GOOGLE_API_KEY_9 }}
          GOOGLE_API_KEY_10: ${{ secrets.GOOGLE_API_KEY_10 }}
          GOOGLE_API_KEY_11: ${{ secrets.GOOGLE_API_KEY_11 }}
        run: python main.py

      - name: Upload All Reports Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Rapports-BRVM-Analyse
          path: |
            ./Rapport_*.docx
            ./Synthese_*.docx
