# ==============================================================================
# FICHIER TEMPORAIRE - WORKFLOW DE TEST POUR LES MODULES DB
# ==============================================================================
name: Full BRVM Analysis Suite

on:
  workflow_dispatch:

jobs:
  run-db-modules-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev build-essential

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run New Data Collector
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: python data_collector.py

      - name: Run New Technical Analyzer
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: python technical_analyzer.py
